service: nodeless

frameworkVersion: '2'

provider:
    name: aws
    runtime: nodejs12.x
    lambdaHashingVersion: 20201221
    region: sa-east-1
    memorySize: 256
    iamRoleStatements:
        - Effect: Allow
          Action:
              - s3:GetObject
              - s3:PutObject
          Resource:
              - 'arn:aws:s3:::*'

functions:
    optimize:
        handler: handler.handle
        environment:
            bucket:
        events:
            - s3:
                  bucket: serverless
                  event: s3:ObjectCreated:*
                  rules:
                      - prefix: uploads/
                      - sufix: .jpg
            - s3:
                  bucket: serverless
                  event: s3:ObjectCreated:*
                  rules:
                      - prefix: uploads/
                      - sufix: .png
